### ISSUE TITLE
トップページの使用量グラフをグレーアウトする

### ISSUE THREAD

**Issue by kamataryo** [geolonia/app.geolonia.com#172]

**Comment by kamataryo** [comment]
![Group](https://user-images.githubusercontent.com/6292312/69314886-91350000-0c78-11ea-987d-0188c7da742d.png)

**Comment by nztm** [comment]
`background-color`と`opacity`を指定してあげるといいのはわかるのですが、
同じdivの中でbackground-colorを指定してしまうとグラフの背景色を上書きすることになってしまい、opacityもかかるものの、要素の中も全部透過されてしまい、、。

要素の外に出してしまうと重ね方がよくわからず...。

**Comment by kamataryo** [comment]
@nztm イメージはこんな感じですかね〜。小要素として準備中を追加して、それを `position: absolite;` にすると重なる気がします！

```jsx
<div className="chart-container">
  <!--  グラフの中身 -->
  <div className="overlap">準備中</div>
</div>
```

```css
.chart-container {
   position: relative;
}
```

```css
.overlap {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  // グレーアウトを追加
}
```

**Comment by nztm** [comment]
ありがとうございます！
しかし、そうすると、グラフの部分だけに適用されてしまい。。
<img width="664" alt="スクリーンショット 2019-11-23 17 03 51" src="https://user-images.githubusercontent.com/43288418/69475698-84004880-0e13-11ea-8451-cc3f7ac46e78.png">

**Comment by kamataryo** [comment]
@nztm となると、もう一つ外側の `.container-map-loads` と `.container-geo-api-loads`ですかね。こっちを `position: relative` にして、 適した場所に子要素を足すとできると思います！

```jsx
<Paper className="container-map-loads">
  <Typography component="h2" className="module-title">
    {__("Map loads for this month")}
  </Typography>
  <div className="chart-container">
     <Line data={mapChartData} options={chartOptions} />
  </div>
  <div className="overlap">準備中</div>
</Paper>
```

**Comment by nztm** [comment]
文字の中心寄せのベストプラクティスがわからないです。
左右は`text-align: center;`でいけると思うんですが、relativeとabsoluteがあったので、
今はこんな感じになっているんですが、うまくいかないらしく..。
```
grayout {
  //ここにグレーアウトの属性
  p {
      top: 50% ;
      transform: translateY(-50%);
  }
}
```

**Comment by nztm** [comment]
グレーアウトのほうはうまくいきました！
ありがとうございます！

**Comment by kamataryo** [comment]
@nztm 文字の上下左右中央寄せは、 FlexBox が一番簡単だと思います！

```css
.overlap {
 display: flex;
  flex-align: center;
  justify-content: center;
}
```

```jsx
<div className="overlap">
  <span>準備中</span>
</div>
```
